"""empty message

Revision ID: 399c6813982a
Revises: 802e52030189
Create Date: 2025-01-22 20:34:28.330142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399c6813982a'
down_revision = '802e52030189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwordResetTokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwordResetTokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
