"""empty message

Revision ID: 3ec3ff443fc5
Revises: c8f2e09f6cdf
Create Date: 2025-01-13 02:08:35.092463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec3ff443fc5'
down_revision = 'c8f2e09f6cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
