"""empty message

Revision ID: 802e52030189
Revises: cdd578094976
Create Date: 2025-01-22 20:21:51.875125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802e52030189'
down_revision = 'cdd578094976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordResetTokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwordResetTokens')
    # ### end Alembic commands ###
