"""empty message

Revision ID: f88dcd04b357
Revises: 5acb96dc3bda
Create Date: 2025-01-03 03:38:07.023250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88dcd04b357'
down_revision = '5acb96dc3bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nif', sa.String(length=9), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=34), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nif')
    )
    op.drop_table('company')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nif', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('client_email_key', type_='unique')
        batch_op.create_unique_constraint('unique_user_nif', ['user_id', 'nif'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timezone')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_user_nif', type_='unique')
        batch_op.create_unique_constraint('client_email_key', ['email'])
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('address')
        batch_op.drop_column('nif')

    op.create_table('company',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('nif', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=34), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='company_pkey'),
    sa.UniqueConstraint('nif', name='company_nif_key')
    )
    op.drop_table('companies')
    # ### end Alembic commands ###
